name: callysto_2i2c
channels:
  - conda-forge
dependencies:
  - altair
  - astropy
  - beautifulsoup4
  - black
  - boto3
  - bokeh
  - bottleneck
  - biopython
  - cartopy
  - cloudpickle
  - colorlover
  - conda-forge::blas=*=openblas
  - cvxopt
  - cython
  - dask
  - dill
  - flake8
  - folium
  - fuzzywuzzy
  - geos
  - geopandas
  - geopy
  - gfortran_linux-64
  - gmp
  - geopandas
  - googletrans
  - gxx_linux-64
  - h5py
  - html5lib
  - imageio
  - ipympl
  - ipysheet
  - ipycanvas
  - ipywidgets
  - jupyterlab-blockly
  - lapack
  - lxml
  - markdown
  - matplotlib-base
  - mpfr
  - mpld3
  - nbconvert
  - nbval
  - nltk
  - numba
  - numexpr
  - nodejs
  - openpyxl
  - pandas
  - patsy
  - plotly
  - proj
  - protobuf
  - psutil
  - pyppeteer
  - pyqt
  - pysal
  - pyspellchecker
  - pytables
  - pytest
  - pytrends
  - r-base
  - r-essentials
  - r-car
  - r-caret
  - r-crayon
  - r-devtools
  - r-dplyr
  - r-forecast
  - r-ggally
  - r-ggplot2
  - r-gmp
  - r-hmisc
  - r-irkernel
  - r-janitor
  - r-languageserver
  - r-lsmeans
  - r-nycflights13
  - r-palmerpenguins
  - r-plyr
  - r-randomforest
  - r-reshape2
  - r-rmarkdown
  - r-rsqlite
  - r-shiny
  - r-stringi
  - r-stringr
  - r-tidyr
  - r-rcurl
  - r-testthat
  - r-tidyverse
  - rdflib
  - rise
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - spacy
  - spacy-model-en_core_web_sm
  - spacy-model-en_core_web_md
  - spacy-model-en_core_web_lg
  - sqlalchemy
  - statsmodels
  - stats_can
  - sympy
  - tensorflow-cpu
  - textblob
  - textstat
  - tqdm
  - vega
  - vega_datasets
  - unidecode
  - widgetsnbextension
  - wikipedia
  - wordcloud
  - xlrd
