name: callysto_2i2c
channels:
  - conda-forge
dependencies:
  - altair
  - astropy
  - beautifulsoup4
  - black
  - boto3
  - bokeh
  - bottleneck
  - biopython
  - cartopy
  - cloudpickle
  - colorlover
  - conda-forge::blas=*=openblas
  - cvxopt
  - cython
  - dask
  - dill
  - flake8
  - folium
  - fuzzywuzzy
  - geos
  - geopandas
  - geopy
  - gfortran_linux-64
  - gmp
  - geopandas
  - googletrans
  - h5py
  - html5lib
  - imageio
  - ipympl
  - ipysheet
  - ipycanvas
  - ipywidgets
  - lapack
  - lxml
  - markdown
  - matplotlib-base
  - mpfr
  - mpld3
  - nbconvert
  - nbval
  - nltk
  - numba
  - numexpr
  - nodejs
  - openpyxl
  - pandas
  - patsy
  - plotly
  - proj
  - protobuf
  - psutil
  - pyqt
  - pysal
  - pyspellchecker
  - pytables
  - pytest
  - pytrends
  - qgrid
  - rdflib
  - rise
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - spacy
  - spacy-model-en_core_web_sm
  - spacy-model-en_core_web_md
  - spacy-model-en_core_web_lg
  - sqlalchemy
  - statsmodels
  - stats_can
  - sympy
  - tensorflow
  - textblob
  - textstat
  - tqdm
  - vega
  - vega_datasets
  - unidecode
  - widgetsnbextension
  - wikipedia
  - wordcloud
  - xlrd
