name: callysto_2i2c
channels:
  - conda-forge
dependencies:
  - altair
  - astropy
  - black
  - boto3
  - beautifulsoup4
  - biopython
  - cartopy
  - colorlover
  - cvxopt
  - flake8
  - folium
  - fuzzywuzzy
  - geos
  - geopandas
  - geopy
  - gfortran_linux-64
  - gmp
  - geopandas
  - googletrans
  - html5lib
  - imageio
  - ipysheet
  - ipycanvas
  - ipywidgets
  - lapack
  - lxml
  - markdown
  - mpfr
  - mpld3
  - nbconvert
  - nbval
  - nltk
  - nodejs
  - openpyxl
  - pandas
  - plotly
  - proj
  - psutil
  - pyqt
  - pysal
  - pyspellchecker
  - pytest
  - pytrends
  - qgrid
  - rdflib
  - rise
  - spacy
  - spacy-model-en_core_web_sm
  - spacy-model-en_core_web_md
  - spacy-model-en_core_web_lg
  - stats_can
  - tensorflow
  - textblob
  - textstat
  - tqdm
  - vega
  - vega_datasets
  - unidecode
  - wikipedia
  - wordcloud
